name: NuclearBomb
version: '${project.version}'
main: top.cmarco.nuclearbomb.NuclearBomb
api-version: '1.13'
authors: [CMarco]
description: "Unleash Destruction on Your Minecraft World!"
commands:
  nuclearbomb:
    description: 'Get nuclear bombs.'
